# Generated by Django 4.2.23 on 2025-10-13 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=50)),
                ('pincode', models.IntegerField(blank=True, null=True)),
                ('dob', models.DateField(blank=True, null=True)),
                ('appointment_time', models.TimeField(blank=True, null=True)),
                ('appointment_date', models.DateField(blank=True, null=True)),
                ('appointment_datetime', models.DateTimeField(blank=True, null=True)),
                ('is_agreed', models.BooleanField(default=False)),
                ('gender', models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=36, null=True)),
                ('interests', models.CharField(blank=True, max_length=100, null=True)),
                ('profile_pic', models.ImageField(blank=True, null=True, upload_to='profile_pics/')),
                ('resume', models.FileField(blank=True, null=True, upload_to='resumes/')),
                ('website', models.URLField(blank=True, null=True)),
                ('mobile_no', models.CharField(blank=True, max_length=15, null=True)),
                ('slug', models.SlugField(blank=True, null=True, unique=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('rating', models.FloatField(blank=True, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('marriedornot', models.BooleanField(default=False)),
                ('split_date_time', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
